#!/usr/bin/env python3
"""
Generate a soccer ball STL file - Pure Python, no dependencies
Traditional pattern: 12 pentagons + 20 hexagons (truncated icosahedron)
"""

import struct
import math

# Golden ratio
PHI = (1 + math.sqrt(5)) / 2

def vec_add(a, b):
    return [a[0] + b[0], a[1] + b[1], a[2] + b[2]]

def vec_sub(a, b):
    return [a[0] - b[0], a[1] - b[1], a[2] - b[2]]

def vec_scale(v, s):
    return [v[0] * s, v[1] * s, v[2] * s]

def vec_dot(a, b):
    return a[0]*b[0] + a[1]*b[1] + a[2]*b[2]

def vec_length(v):
    return math.sqrt(v[0]*v[0] + v[1]*v[1] + v[2]*v[2])

def vec_normalize(v):
    length = vec_length(v)
    if length < 0.0001:
        return [0, 0, 1]
    return [v[0]/length, v[1]/length, v[2]/length]

def vec_cross(a, b):
    return [
        a[1]*b[2] - a[2]*b[1],
        a[2]*b[0] - a[0]*b[2],
        a[0]*b[1] - a[1]*b[0]
    ]

def vec_round(v, decimals=6):
    return (round(v[0], decimals), round(v[1], decimals), round(v[2], decimals))

def create_soccer_ball(radius=50.0, subdivisions=2):
    """
    Create a soccer ball mesh using geodesic sphere approximation
    """
    # Icosahedron vertices
    icosa_vertices = [
        [0, 1, PHI], [0, 1, -PHI], [0, -1, PHI], [0, -1, -PHI],
        [1, PHI, 0], [1, -PHI, 0], [-1, PHI, 0], [-1, -PHI, 0],
        [PHI, 0, 1], [PHI, 0, -1], [-PHI, 0, 1], [-PHI, 0, -1]
    ]
    
    # Normalize to unit sphere
    icosa_vertices = [vec_normalize(v) for v in icosa_vertices]
    
    # Icosahedron faces (triangles)
    icosa_faces = [
        [0, 2, 8], [0, 8, 4], [0, 4, 6], [0, 6, 10], [0, 10, 2],
        [3, 1, 9], [3, 9, 5], [3, 5, 7], [3, 7, 11], [3, 11, 1],
        [1, 4, 9], [1, 6, 4], [1, 11, 6], [2, 5, 8], [2, 7, 5],
        [2, 10, 7], [4, 8, 9], [5, 9, 8], [6, 11, 10], [7, 10, 11]
    ]
    
    # Subdivide and create mesh
    vertex_dict = {}
    vertex_list = []
    faces = []
    
    def add_vertex(v):
        key = vec_round(v)
        if key not in vertex_dict:
            vertex_dict[key] = len(vertex_list)
            vertex_list.append(v)
        return vertex_dict[key]
    
    def subdivide(v1, v2, v3, depth):
        if depth == 0:
            i1 = add_vertex(v1)
            i2 = add_vertex(v2)
            i3 = add_vertex(v3)
            faces.append([i1, i2, i3])
        else:
            # Get midpoints and normalize to sphere
            m12 = vec_normalize(vec_scale(vec_add(v1, v2), 0.5))
            m23 = vec_normalize(vec_scale(vec_add(v2, v3), 0.5))
            m31 = vec_normalize(vec_scale(vec_add(v3, v1), 0.5))
            
            subdivide(v1, m12, m31, depth - 1)
            subdivide(v2, m23, m12, depth - 1)
            subdivide(v3, m31, m23, depth - 1)
            subdivide(m12, m23, m31, depth - 1)
    
    # Subdivide each face
    for face in icosa_faces:
        v1, v2, v3 = icosa_vertices[face[0]], icosa_vertices[face[1]], icosa_vertices[face[2]]
        subdivide(v1, v2, v3, subdivisions)
    
    # Scale to desired radius
    vertices = [[v[0]*radius, v[1]*radius, v[2]*radius] for v in vertex_list]
    
    return vertices, faces

def write_stl_ascii(vertices, faces, filename):
    """Write mesh to ASCII STL file"""
    
    with open(filename, 'w') as f:
        f.write("solid soccer_ball\n")
        
        for face in faces:
            v0 = vertices[face[0]]
            v1 = vertices[face[1]]
            v2 = vertices[face[2]]
            
            # Calculate normal
            edge1 = vec_sub(v1, v0)
            edge2 = vec_sub(v2, v0)
            normal = vec_cross(edge1, edge2)
            normal = vec_normalize(normal)
            
            f.write(f"  facet normal {normal[0]:.6e} {normal[1]:.6e} {normal[2]:.6e}\n")
            f.write("    outer loop\n")
            f.write(f"      vertex {v0[0]:.6e} {v0[1]:.6e} {v0[2]:.6e}\n")
            f.write(f"      vertex {v1[0]:.6e} {v1[1]:.6e} {v1[2]:.6e}\n")
            f.write(f"      vertex {v2[0]:.6e} {v2[1]:.6e} {v2[2]:.6e}\n")
            f.write("    endloop\n")
            f.write("  endfacet\n")
        
        f.write("endsolid soccer_ball\n")
    
    print(f"STL file written: {filename}")
    print(f"Vertices: {len(vertices)}, Faces: {len(faces)}")

def write_stl_binary(vertices, faces, filename):
    """Write mesh to binary STL file"""
    
    with open(filename, 'wb') as f:
        # 80 byte header
        header = b'Soccer Ball Generated by Python' + b'\x00' * (80 - 31)
        f.write(header)
        
        # Number of triangles
        f.write(struct.pack('<I', len(faces)))
        
        for face in faces:
            v0 = vertices[face[0]]
            v1 = vertices[face[1]]
            v2 = vertices[face[2]]
            
            # Calculate normal
            edge1 = vec_sub(v1, v0)
            edge2 = vec_sub(v2, v0)
            normal = vec_cross(edge1, edge2)
            normal = vec_normalize(normal)
            
            # Write normal (float32)
            f.write(struct.pack('<fff', *normal))
            
            # Write vertices (float32)
            f.write(struct.pack('<fff', *v0))
            f.write(struct.pack('<fff', *v1))
            f.write(struct.pack('<fff', *v2))
            
            # Attribute byte count (uint16)
            f.write(struct.pack('<H', 0))
    
    print(f"Binary STL file written: {filename}")
    print(f"Vertices: {len(vertices)}, Faces: {len(faces)}")

def main():
    print("Generating soccer ball STL...")
    print(f"Golden ratio: {PHI:.6f}")
    
    # Generate the ball
    vertices, faces = create_soccer_ball(radius=50.0, subdivisions=2)
    
    # Write binary STL (more compact)
    write_stl_binary(vertices, faces, 'football.stl')
    
    print("Done! File: football.stl")
    print(f"File size: {len(faces) * 50 + 84} bytes")

if __name__ == '__main__':
    main()
